#!/usr/bin/env node

const path = require('path')
const wallpaper = require('wallpaper')
const date = new Date()
const hour = date.getHours()
const filepath = path.join(process.env.IMG_DIR, `gradient-${hour}-${process.env.GID}.png`)

wallpaper.set(filepath, { scale: 'fill' })
  .then(() => {
    console.log('Set wallpaper:', filepath,'| time:', date.toTimeString().substring(0, 8));
  })
  .catch(console.error)
